### PR TITLE
Fix: Korean translation

### PR DESCRIPTION
**Pull request by telk5093**
There was a typo ;)
\+ Gender for industry names

### CODE REVIEW

**Review by andythenorth — APPROVED** [review]

**Comment by andythenorth** [comment]
Hi Telk,

Unfortunately this conflicts when I try to merge it to current main branch, and I'm not able to judge how to resolve the conflict sorry.

The conflicts are listed here: https://github.com/andythenorth/firs/pull/15/conflicts

**Comment by telk5093** [comment]
Is it solved now? 😅

**Comment by telk5093** [comment]
Thanks for letting me know, now fixed 🙂

**Comment by telk5093** [comment]
@andythenorth Any news???

**Comment by telk5093** [comment]
Close since 5.0.0-beta1 is released

**Pull request closed without merging**
